name: MailMentor CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install spaCy model
      run: |
        python -m spacy download en_core_web_sm
    
    - name: Set env
      run: |
        echo "DATABASE_URL=sqlite:///./test.db" >> $GITHUB_ENV
        echo "SECRET_KEY=testsecret" >> $GITHUB_ENV
        echo "GROQ_API_KEY=dummy" >> $GITHUB_ENV
        echo "TESTING=1" >> $GITHUB_ENV

    - name: Run tests
      run: |
        python -m pytest -v